@extends('layouts.app')
@section('title', $student->name)
@section('content')
    <div class="breadcrumb"><a href="{{ route('families.show', $student->family) }}">{{ $student->family->family_code }}</a><span class="breadcrumb-sep">/</span><span>{{ $student->name }}</span></div>
    <div class="print-record">
    <x-page-header :title="$student->name" :subtitle="$student->admission_no" eyebrow="Registration" />
    <div class="page-actions"><button class="btn btn-secondary" type="button" onclick="window.print()" data-testid="student-print-button">Print student details</button><x-button-link :href="route('students.edit', $student)">Edit student</x-button-link><x-button-link :href="route('families.show', $student->family)" variant="quiet">Back to family</x-button-link></div>
    <x-card title="Student details"><dl class="kv"><div class="kv-row"><dt>Family</dt><dd>{{ $student->family->family_code }}</dd></div><div class="kv-row"><dt>Date of birth</dt><dd>{{ $student->dob->toDateString() }}</dd></div><div class="kv-row"><dt>Gender</dt><dd>{{ $student->gender }}</dd></div><div class="kv-row"><dt>Status</dt><dd><x-status-badge :value="$student->status" /></dd></div><div class="kv-row"><dt>Photo path</dt><dd>{{ $student->photo_path }}</dd></div></dl></x-card>
    <x-card title="Guardian access"><form class="print-hide" method="POST" action="{{ route('students.guardians.store', $student) }}" data-loading>@csrf<select class="form-control" name="guardian_id" required><option value="">-- link a guardian from this family --</option>@foreach ($student->family->guardians as $guardian)<option value="{{ $guardian->id }}">{{ $guardian->name }}</option>@endforeach</select><div class="btn-row"><button class="btn btn-secondary" type="submit">Link guardian</button></div></form><div class="table-wrap"><table class="table"><thead><tr><th>Guardian</th><th>Relationship</th><th class="actions">Actions</th></tr></thead><tbody>@forelse ($student->guardians as $guardian)<tr><td>{{ $guardian->name }}</td><td>{{ $guardian->relationship }}</td><td class="actions"><form method="POST" action="{{ route('students.guardians.destroy', [$student, $guardian]) }}" data-confirm="Revoke this guardian's access to this student?" data-loading>@csrf @method('DELETE')<button type="submit" class="btn btn-danger btn-small">Revoke access</button></form></td></tr>@empty<tr class="table-empty"><td colspan="3">No guardian is linked. Family membership alone grants no student visibility.</td></tr>@endforelse</tbody></table></div></x-card>
    <x-card title="Enrollments"><div class="table-wrap"><table class="table"><thead><tr><th>Academic year</th><th>Current placement</th><th>Placement history</th><th class="actions">Actions</th></tr></thead><tbody>@forelse ($student->enrollments as $enrollment)<tr><td>{{ $enrollment->academicYear->name }}</td><td>{{ $enrollment->grade->name }} {{ $enrollment->section->name }}</td><td>{{ $enrollment->placements->map(fn ($placement) => $placement->grade->name.' '.$placement->section->name)->join(' → ') ?: 'No moves recorded' }}</td><td class="actions"><x-button-link :href="route('enrollments.placements.create', $enrollment)" variant="quiet" size="small">Record placement</x-button-link></td></tr>@empty<tr class="table-empty"><td colspan="4">No enrollments recorded.</td></tr>@endforelse</tbody></table></div></x-card>
    <x-card title="Discounts"><p>{{ $student->discounts->count() }} recorded discount(s).</p><x-button-link :href="route('students.discounts.index', $student)" variant="secondary" class="print-hide">Manage discounts</x-button-link></x-card>
    <x-card title="Fee subscriptions"><p>{{ $student->studentFeeSubscriptions->count() }} recorded subscription(s).</p><x-button-link :href="route('students.fee-subscriptions.index', $student)" variant="secondary" class="print-hide">Manage fee subscriptions</x-button-link></x-card>
    </div>
@endsection
